### ISSUE TITLE
TypeError: Cannot read property 'setGenericPasswordForOptions' of undefined

### ISSUE THREAD

**Issue by leizard** [oblador/react-native-keychain#59]
I use Keychain as basic example:

```
      Keychain
      .setGenericPassword('myUserName', 'myPassword')
      .then(() => {
        console.log('Credentials saved successfully!');
      });
```

but this error happens:

<img width="537" alt="screen shot 2017-03-09 at 22 13 24" src="https://cloud.githubusercontent.com/assets/5291692/23756340/f06d9ac2-0515-11e7-8a3d-9457c996366a.png">
 Do you have any idea why ?

**Comment by vonovak** [comment]
on what platform do you have the issue? have you tried following the manual installation instructions to check everything's set up properly? are you using the right package version for your RN version? (there was breaking change for in 0.40 I believe)

**Comment by MaxMillington** [comment]
@leizard Yes I'm getting a similar error after upgrading to the current version in order to accommodate the breaking changes introduced by RN 0.40

**Comment by Armageddonas** [comment]
Got a similar error. After updating to `RN 0.42.3` and restarting the app with the commands
```bash
react-native run-android
react-native start --reset-cache
```
it is working properly. Was it the restart or the update, i don't know.

**Comment by dannyharding10** [comment]
I had a similar error, but it was fixed when I restarted using `react-native run-ios`

**Comment by driedelreply** [comment]
having the same problem. Restart and update didn't work.

using:
```
    "react-native": "0.43.4",
    "react-native-keychain": "^1.2.0",
```

**Comment by wmak** [comment]
Had this problem, was solved by running [read more here](https://facebook.github.io/react-native/docs/linking-libraries-ios.html)
```
react-native link
react-native run-ios # or run-android
```

**Comment by amywangcs** [comment]
Running this version combo:
    "react-native": "0.43.2",
    "react-native-keychain": "^2.0.0-rc",

But the issue still existing, after running:
react-native link
react-native run-ios

Any tips for a working combo of RN and RNK? Thanks much!

**Comment by priya-vr** [comment]
I am getting same error when calling setGenericPasswordForOptions,My RN version is
        
    {
		"react-native": "0.46.4",
		"react-native-keychain": "2.0.0-rc",
}
But the issue still existing, after running:
react-native link
react-native run-ios.Please give any tips for solving problem

**Comment by wmak** [comment]
Unable to test to confirm if this will help, but generally my debug process would be to:
- Kill anything running (the window that run-ios opens, the simulator etc.)
- Delete `node_modules` run `npm install` again
- Create a new RN project and copy code over and try again
- Update to newest `react-native` version (don't forget that if you do this you'll probably want to init your entire project again)
- Node also caches some stuff in your home directory, if after all of the above it's still not working, it might be worth deleting the cached files and retrying the step all over again.

**Comment by priya-vr** [comment]
@wmak  ,Thanks for the replay, I had tried all these steps, But getting same error

**Comment by leohliao** [comment]
I am also having the same error. 
my RN version is  
`    "react-native": "^0.46.1",
      "react-native-keychain": "^2.0.0-rc",
`
- I linked my files with `react-native link` and `rnpm link react-native-keychain`. 
- Went to Xcode to change my keychain settings. 
- I also changed  import method to `import * as Keychain from 'react-native-keychain';`
- I did reset my cache
..... i am using `npm run ios` where `ios` is `react-native-scripts ios` instead of using `react-native run-ios` 
...none of the above i did helped....
I don't know if the issue happens because i didn't use `index-ios.js` as my entry file... hope someone finds the solution.

**Comment by vonovak** [comment]
hello, please check my first comment, especially the part about manual installation (try to install manually)

**Comment by 8ofproject** [comment]
@vonovak tried the manual approach on android. Still getting the same error.

**Comment by 8ofproject** [comment]
Package is not accessible for some reason.
Checked with this code:
```
try {
  require.resolve('react-native-keychain');
} catch(e){
  console.warn('Package not accessible');
}
```

**Comment by wmak** [comment]
Hey @oblador. I think this issue should be closed, it seems to be more a config issue on the client end rather than an issue with this library.

**Comment by ttaranov** [comment]
this error goes away after a clean rebuild: rm -rf ios/build && react-native run-ios

**Comment by oblador** [comment]
@wmak Yup, closing 👍

**Comment by GabrielMerigo** [comment]
I had the same issue... I just deleted node_modules and installed it again :)
```
yarn -> 1.22.09
---
"react-native": "0.72.7
"react-native-keychain": "^8.1.2"
```
